### ISSUE TITLE
The application is not thread safe

### ISSUE THREAD

**Issue by mvrueden** [Keybird/beagle#45]
At the moment multiple threads can CRUD data at the same time. But the application itself does not support this.
Especially the entities are not protected. For example an Index/Import-Job may still be running and modify an entity, where a DELETE request against the rest api is made and deletes those currently in use entities. As this is at the moment only a test scenario, this should be prevented in general.

**Comment by mvrueden** [comment]
Finally got an exception indicating what I was talking about:

``` 
 app_1            | java.util.ConcurrentModificationException: null
app_1            | 	at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1237) ~[na:1.8.0_151]
app_1            | 	at java.util.ArrayList$SubList.size(ArrayList.java:1046) ~[na:1.8.0_151]
app_1            | 	at de.keybird.beagle.jobs.execution.IndexJobExecution.execute(IndexJobExecution.java:98) ~[classes!/:0.0.1-SNAPSHOT]
app_1            | 	at de.keybird.beagle.jobs.execution.JobRunner.execute(JobRunner.java:53) ~[classes!/:0.0.1-SNAPSHOT]
app_1            | 	at de.keybird.beagle.jobs.JobExecutionManager.lambda$null$1(JobExecutionManager.java:126) ~[classes!/:0.0.1-SNAPSHOT]
app_1            | 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
app_1            | 	at de.keybird.beagle.jobs.JobExecutionManager.lambda$submit$2(JobExecutionManager.java:125) ~[classes!/:0.0.1-SNAPSHOT]
app_1            | 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_151]
app_1            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
app_1            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
app_1            | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

**Comment by mvrueden** [comment]
The issue mentioned here was already addressed a while ago. Most of the thread safety issues were addressed with PR https://github.com/Keybird/beagle/pull/60. Closing for now.
